# Generated by Django 5.2.1 on 2025-08-26 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('vendor_name', models.CharField(max_length=255)),
                ('billing_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('gstn', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('short_intro', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_till', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='boe_num',
            field=models.TextField(default=None),
        ),
        migrations.CreateModel(
            name='TripOutToVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_capacity', models.DecimalField(decimal_places=2, help_text='Capacity in MT', max_digits=6)),
                ('from_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('kilometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_bill_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('In-Progress', 'In-Progress'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed'), ('Hold', 'Hold')], default='In-Progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='main.vendormaster')),
            ],
        ),
    ]
