# Generated by Django 5.2.1 on 2025-08-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='pod_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
