# Generated by Django 5.2.1 on 2025-08-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shipment_pod_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='billto_customer',
            field=models.ForeignKey(blank=True, db_column='billto_customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='main.customermaster', to_field='customer_id'),
        ),
    ]
