# Generated by Django 5.2.1 on 2025-08-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shipment_billto_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='ewaybill_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='invoice_ref_number',
            field=models.CharField(max_length=500),
        ),
    ]
